In [3]:
import pandas as pd

# Load the entire Parquet file into a DataFrame
df_2025 = pd.read_parquet('yellow_tripdata_2025-01.parquet')
print(df_2025.head())

   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         1  2025-01-01 00:18:38   2025-01-01 00:26:59              1.0
1         1  2025-01-01 00:32:40   2025-01-01 00:35:13              1.0
2         1  2025-01-01 00:44:04   2025-01-01 00:46:01              1.0
3         2  2025-01-01 00:14:27   2025-01-01 00:20:01              3.0
4         2  2025-01-01 00:21:34   2025-01-01 00:25:06              3.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           1.60         1.0                  N           229           237
1           0.50         1.0                  N           236           237
2           0.60         1.0                  N           141           141
3           0.52         1.0                  N           244           244
4           0.66         1.0                  N           244           116

   payment_type  fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
0             1         10.0    3.5      0.5        3.00           0.0
1             1          5.1    3.5      0.5        2.02           0.0
2             1          5.1    3.5      0.5        2.00           0.0
3             2          7.2    1.0      0.5        0.00           0.0
4             2          5.8    1.0      0.5        0.00           0.0

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0         18.00                   2.5          0.0
1                    1.0         12.12                   2.5          0.0
2                    1.0         12.10                   2.5          0.0
3                    1.0          9.70                   0.0          0.0
4                    1.0          8.30                   0.0          0.0

   cbd_congestion_fee
0                 0.0
1                 0.0
2                 0.0
3                 0.0
4                 0.0

In [4]:
df_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3475226 entries, 0 to 3475225
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[ns](2), float64(13), int32(3), int64(1), object(1)
memory usage: 490.5+ MB

In [5]:
df_2025.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee'],
      dtype='object')

In [6]:
df_2025.isna().sum()

VendorID                      0
tpep_pickup_datetime          0
tpep_dropoff_datetime         0
passenger_count          540149
trip_distance                 0
RatecodeID               540149
store_and_fwd_flag       540149
PULocationID                  0
DOLocationID                  0
payment_type                  0
fare_amount                   0
extra                         0
mta_tax                       0
tip_amount                    0
tolls_amount                  0
improvement_surcharge         0
total_amount                  0
congestion_surcharge     540149
Airport_fee              540149
cbd_congestion_fee            0
dtype: int64

In [7]:
trip25=df_2025
trip25

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.00,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.00
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.10,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.00
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.10,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.00
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.20,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.00
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.80,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475221,2,2025-01-31 23:01:48,2025-01-31 23:16:29,NaN,3.35,NaN,None,79,237,0,15.85,0.0,0.5,0.00,0.0,1.0,20.60,NaN,NaN,0.75
3475222,2,2025-01-31 23:50:29,2025-02-01 00:17:27,NaN,8.73,NaN,None,161,116,0,28.14,0.0,0.5,0.00,0.0,1.0,32.89,NaN,NaN,0.75
3475223,2,2025-01-31 23:26:59,2025-01-31 23:43:01,NaN,2.64,NaN,None,144,246,0,14.91,0.0,0.5,0.00,0.0,1.0,19.66,NaN,NaN,0.75
3475224,2,2025-01-31 23:14:34,2025-01-31 23:34:52,NaN,3.16,NaN,None,142,107,0,17.55,0.0,0.5,0.00,0.0,1.0,22.30,NaN,NaN,0.75
3475225,2,2025-01-31 23:56:42,2025-02-01 00:07:27,NaN,2.29,NaN,None,237,238,0,12.09,0.0,0.5,0.00,0.0,1.0,16.09,NaN,NaN,0.00

In [8]:
df_2025['RatecodeID'].describe()

count    2.935077e+06
mean     2.482535e+00
std      1.163277e+01
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      9.900000e+01
Name: RatecodeID, dtype: float64

In [9]:
df_2025[df_2025['RatecodeID'] == 5]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
98,2,2025-01-01 00:04:29,2025-01-01 00:55:58,9.0,31.97,5.0,N,132,265,2,90.00,0.0,0.0,0.00,20.32,1.0,111.32,0.0,0.0,0.00
164,2,2025-01-01 00:48:53,2025-01-01 01:13:31,1.0,11.81,5.0,N,68,265,1,80.00,0.0,0.0,0.00,21.38,1.0,102.38,0.0,0.0,0.00
204,2,2025-01-01 00:37:43,2025-01-01 00:37:53,1.0,0.00,5.0,N,148,148,1,12.00,0.0,0.0,2.00,0.00,1.0,17.50,2.5,0.0,0.00
288,2,2025-01-01 00:26:09,2025-01-01 00:51:09,1.0,5.69,5.0,N,186,265,1,60.00,0.0,0.0,14.88,13.38,1.0,89.26,0.0,0.0,0.00
358,2,2025-01-01 00:57:08,2025-01-01 00:57:16,3.0,0.00,5.0,N,141,141,1,30.00,0.0,0.0,0.00,0.00,1.0,33.50,2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2934739,2,2025-01-31 23:22:56,2025-01-31 23:23:16,1.0,0.04,5.0,N,164,164,1,20.21,0.0,0.0,1.00,0.00,1.0,25.46,2.5,0.0,0.75
2934740,2,2025-01-31 23:31:22,2025-01-31 23:31:32,1.0,0.00,5.0,N,79,79,1,14.88,0.0,0.0,1.00,0.00,1.0,20.13,2.5,0.0,0.75
2934741,2,2025-01-31 23:41:48,2025-01-31 23:41:54,1.0,0.00,5.0,N,249,249,1,10.21,0.0,0.0,2.00,0.00,1.0,16.46,2.5,0.0,0.75
2934751,2,2025-01-31 23:02:15,2025-01-31 23:02:28,1.0,0.00,5.0,N,68,68,1,150.00,0.0,0.0,0.00,0.00,1.0,154.25,2.5,0.0,0.75
2934975,2,2025-01-31 23:04:58,2025-01-31 23:27:13,4.0,3.52,5.0,N,234,148,1,35.00,0.0,0.0,0.00,0.00,1.0,39.25,2.5,0.0,0.75

In [10]:
df_2025.duplicated().sum()

0

#### Vendor Exploration

In [11]:
df_2025["VendorID"].describe()

count    3.475226e+06
mean     1.785428e+00
std      4.263282e-01
min      1.000000e+00
25%      2.000000e+00
50%      2.000000e+00
75%      2.000000e+00
max      7.000000e+00
Name: VendorID, dtype: float64

In [12]:
cmt_vendor=df_2025[df_2025["VendorID"] == 1]
cmt_vendor

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.6,1.0,N,229,237,1,10.00,3.5,0.5,3.00,0.00,1.0,18.00,2.5,0.0,0.00
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.5,1.0,N,236,237,1,5.10,3.5,0.5,2.02,0.00,1.0,12.12,2.5,0.0,0.00
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.6,1.0,N,141,141,1,5.10,3.5,0.5,2.00,0.00,1.0,12.10,2.5,0.0,0.00
6,1,2025-01-01 00:14:47,2025-01-01 00:16:15,0.0,0.4,1.0,N,170,170,1,4.40,3.5,0.5,2.35,0.00,1.0,11.75,2.5,0.0,0.00
7,1,2025-01-01 00:39:27,2025-01-01 00:51:51,0.0,1.6,1.0,N,234,148,1,12.10,3.5,0.5,2.00,0.00,1.0,19.10,2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475141,1,2025-01-31 23:40:42,2025-01-31 23:47:47,NaN,0.7,NaN,None,79,148,0,7.36,0.0,0.5,0.00,0.00,1.0,12.11,NaN,NaN,0.75
3475142,1,2025-01-31 23:02:31,2025-01-31 23:30:48,NaN,10.5,NaN,None,247,4,0,37.65,0.0,0.5,0.00,6.94,1.0,49.34,NaN,NaN,0.75
3475157,1,2025-01-31 23:10:25,2025-01-31 23:36:21,NaN,0.0,NaN,None,144,263,0,22.25,2.0,0.5,4.60,0.00,1.0,35.60,NaN,NaN,0.75
3475167,1,2025-01-31 23:58:09,2025-02-01 00:24:37,NaN,3.9,NaN,None,142,79,0,26.71,0.0,0.5,0.00,0.00,1.0,31.46,NaN,NaN,0.75
3475188,1,2025-01-31 23:47:55,2025-01-31 23:57:40,NaN,1.0,NaN,None,144,148,0,9.30,1.0,0.5,2.25,0.00,1.0,17.30,NaN,NaN,0.75

In [13]:
cml_vendor=df_2025[df_2025["VendorID"] == 2]
cml_vendor

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.20,1.0,0.5,0.0,0.0,1.0,9.70,0.0,0.0,0.00
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.80,1.0,0.5,0.0,0.0,1.0,8.30,0.0,0.0,0.00
5,2,2025-01-01 00:48:24,2025-01-01 01:08:26,2.0,2.63,1.0,N,239,68,2,19.10,1.0,0.5,0.0,0.0,1.0,24.10,2.5,0.0,0.00
9,2,2025-01-01 00:00:02,2025-01-01 00:09:36,1.0,1.71,1.0,N,237,262,2,11.40,1.0,0.5,0.0,0.0,1.0,16.40,2.5,0.0,0.00
10,2,2025-01-01 00:20:28,2025-01-01 00:28:04,1.0,2.29,1.0,N,237,75,2,11.40,1.0,0.5,0.0,0.0,1.0,16.40,2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475221,2,2025-01-31 23:01:48,2025-01-31 23:16:29,NaN,3.35,NaN,None,79,237,0,15.85,0.0,0.5,0.0,0.0,1.0,20.60,NaN,NaN,0.75
3475222,2,2025-01-31 23:50:29,2025-02-01 00:17:27,NaN,8.73,NaN,None,161,116,0,28.14,0.0,0.5,0.0,0.0,1.0,32.89,NaN,NaN,0.75
3475223,2,2025-01-31 23:26:59,2025-01-31 23:43:01,NaN,2.64,NaN,None,144,246,0,14.91,0.0,0.5,0.0,0.0,1.0,19.66,NaN,NaN,0.75
3475224,2,2025-01-31 23:14:34,2025-01-31 23:34:52,NaN,3.16,NaN,None,142,107,0,17.55,0.0,0.5,0.0,0.0,1.0,22.30,NaN,NaN,0.75
3475225,2,2025-01-31 23:56:42,2025-02-01 00:07:27,NaN,2.29,NaN,None,237,238,0,12.09,0.0,0.5,0.0,0.0,1.0,16.09,NaN,NaN,0.00

In [14]:
mti_vendor=df_2025[df_2025["VendorID"] == 6]
mti_vendor

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
2943550,6,2025-01-01 04:01:08,2025-01-01 05:01:21,NaN,11.53,NaN,None,230,85,0,2.9,0.0,0.5,0.0,0.00,0.3,41.56,NaN,NaN,0.0
2943551,6,2025-01-01 04:01:42,2025-01-01 04:01:58,NaN,16.16,NaN,None,48,39,0,2.9,0.0,0.5,0.0,6.94,0.3,48.69,NaN,NaN,0.0
2945108,6,2025-01-01 08:01:12,2025-01-01 08:01:30,NaN,15.95,NaN,None,68,205,0,2.9,0.0,0.5,0.0,6.94,0.3,53.19,NaN,NaN,0.0
2945109,6,2025-01-01 08:01:34,2025-01-01 09:01:33,NaN,17.31,NaN,None,215,94,0,2.9,0.0,0.5,0.0,6.94,0.3,49.72,NaN,NaN,0.0
2945258,6,2025-01-01 09:01:32,2025-01-01 10:01:00,NaN,12.30,NaN,None,101,242,0,2.9,0.0,0.5,0.0,6.94,0.3,47.69,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3452675,6,2025-01-31 14:01:49,2025-01-31 14:01:52,NaN,0.42,NaN,None,250,212,0,2.9,0.0,0.5,0.0,0.00,0.3,16.00,NaN,NaN,0.0
3453139,6,2025-01-31 15:01:46,2025-01-31 16:01:36,NaN,11.05,NaN,None,140,131,0,2.9,0.0,0.5,0.0,0.00,0.3,48.08,NaN,NaN,0.0
3453194,6,2025-01-31 15:01:51,2025-01-31 16:01:35,NaN,18.11,NaN,None,170,117,0,2.9,0.0,0.5,0.0,9.54,0.3,64.64,NaN,NaN,0.0
3468302,6,2025-01-31 21:01:13,2025-01-31 21:01:44,NaN,7.55,NaN,None,137,167,0,2.9,0.0,0.5,0.0,0.00,0.3,25.16,NaN,NaN,0.0
3469543,6,2025-01-31 22:01:03,2025-01-31 22:01:59,NaN,1.66,NaN,None,116,119,0,2.9,0.0,0.5,0.0,0.00,0.3,16.00,NaN,NaN,0.0

In [15]:
helix_vendor=df_2025[df_2025["VendorID"] == 7]
helix_vendor

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
31891,7,2025-01-01 12:44:07,2025-01-01 12:44:07,2.0,1.56,1.0,N,143,230,1,17.0,0.0,0.5,10.00,0.0,1.0,31.00,2.5,0.0,0.00
35475,7,2025-01-01 13:28:23,2025-01-01 13:28:23,2.0,2.06,1.0,N,239,230,1,13.5,0.0,0.5,3.50,0.0,1.0,21.00,2.5,0.0,0.00
39599,7,2025-01-01 14:46:59,2025-01-01 14:46:59,2.0,0.87,1.0,N,170,234,1,7.2,0.0,0.5,2.24,0.0,1.0,13.44,2.5,0.0,0.00
44063,7,2025-01-01 15:59:11,2025-01-01 15:59:11,2.0,1.49,1.0,N,68,113,1,9.3,0.0,0.5,3.99,0.0,1.0,17.29,2.5,0.0,0.00
48564,7,2025-01-01 16:50:09,2025-01-01 16:50:09,1.0,2.53,1.0,N,161,144,1,14.9,0.0,0.5,5.35,0.0,1.0,26.75,2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2930236,7,2025-01-31 23:09:50,2025-01-31 23:09:50,1.0,5.13,1.0,N,107,41,1,24.7,0.0,0.5,6.09,0.0,1.0,36.54,2.5,0.0,0.75
2930237,7,2025-01-31 23:40:04,2025-01-31 23:40:04,1.0,0.66,1.0,N,43,230,1,5.1,0.0,0.5,2.17,0.0,1.0,13.02,2.5,0.0,0.75
2930279,7,2025-01-31 23:28:06,2025-01-31 23:28:06,1.0,1.37,1.0,N,161,236,1,7.2,0.0,0.5,2.59,0.0,1.0,15.54,2.5,0.0,0.75
2930280,7,2025-01-31 23:43:51,2025-01-31 23:43:51,1.0,1.13,1.0,N,237,43,1,7.2,0.0,0.5,2.44,0.0,1.0,14.64,2.5,0.0,0.00
2931042,7,2025-01-31 23:48:18,2025-01-31 23:48:18,2.0,2.43,1.0,N,142,151,1,13.5,0.0,0.5,4.81,0.0,1.0,24.06,2.5,0.0,0.75

In [16]:
df_2025[~df_2025["VendorID"].isin([1,2,6,7])]

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, Airport_fee, cbd_congestion_fee]
Index: []

In [17]:
df_2025['tpep_pickup_datetime'].describe()

count                          3475226
mean     2025-01-17 11:02:55.910962944
min                2024-12-31 20:47:55
25%                2025-01-10 07:59:01
50%                2025-01-17 15:41:33
75%                2025-01-24 19:34:06
max                2025-02-01 00:00:44
Name: tpep_pickup_datetime, dtype: object

In [18]:
trips_2024 = df_2025[(df_2025['tpep_pickup_datetime'].dt.year == 2024) & (df_2025['tpep_dropoff_datetime'].dt.year == 2024)]
trips_2024

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
605,2,2024-12-31 23:30:03,2024-12-31 23:43:02,1.0,3.00,1.0,N,246,13,1,16.3,1.0,0.5,5.32,0.0,1.0,26.62,2.5,0.00,0.0
687,2,2024-12-31 23:31:38,2024-12-31 23:41:48,1.0,1.03,1.0,N,43,140,2,10.7,1.0,0.5,0.00,0.0,1.0,15.70,2.5,0.00,0.0
2276,2,2024-12-31 23:49:24,2024-12-31 23:57:30,1.0,2.44,1.0,N,142,151,1,12.1,1.0,0.5,3.42,0.0,1.0,20.52,2.5,0.00,0.0
3941,2,2024-12-31 23:27:13,2024-12-31 23:35:48,1.0,1.53,1.0,N,170,141,1,10.0,1.0,0.5,3.00,0.0,1.0,18.00,2.5,0.00,0.0
3942,2,2024-12-31 23:37:42,2024-12-31 23:43:10,1.0,0.92,1.0,N,229,141,1,7.2,1.0,0.5,1.83,0.0,1.0,14.03,2.5,0.00,0.0
4654,2,2024-12-31 23:24:31,2024-12-31 23:25:35,5.0,0.28,1.0,N,132,132,2,3.7,1.0,0.5,0.00,0.0,1.0,7.95,0.0,1.75,0.0
5217,2,2024-12-31 23:48:48,2024-12-31 23:55:13,1.0,0.99,1.0,N,114,148,1,7.9,1.0,0.5,3.00,0.0,1.0,15.90,2.5,0.00,0.0
7623,2,2024-12-31 20:47:55,2024-12-31 20:54:00,2.0,1.72,1.0,N,48,246,1,9.3,1.0,0.5,2.86,0.0,1.0,17.16,2.5,0.00,0.0
7624,2,2024-12-31 20:54:50,2024-12-31 21:30:18,2.0,1.39,1.0,N,246,48,1,28.2,1.0,0.5,6.64,0.0,1.0,39.84,2.5,0.00,0.0
7625,2,2024-12-31 21:20:05,2024-12-31 21:35:13,2.0,2.64,1.0,N,42,238,1,16.3,1.0,0.5,2.00,0.0,1.0,23.30,2.5,0.00,0.0
17542,2,2024-12-31 20:52:50,2024-12-31 21:09:34,2.0,5.05,1.0,N,249,262,1,23.3,1.0,0.5,4.00,0.0,1.0,32.30,2.5,0.00,0.0
20611,2,2024-12-31 21:15:22,2024-12-31 21:26:00,2.0,3.20,1.0,N,141,146,1,15.6,1.0,0.5,3.00,0.0,1.0,23.60,2.5,0.00,0.0
20612,2,2024-12-31 21:33:43,2024-12-31 21:39:00,2.0,1.12,1.0,N,179,7,2,7.9,1.0,0.5,0.00,0.0,1.0,10.40,0.0,0.00,0.0

In [19]:
df_2025['tpep_dropoff_datetime'].describe()

count                          3475226
mean     2025-01-17 11:17:56.997899776
min                2024-12-18 07:52:40
25%         2025-01-10 08:15:29.500000
50%                2025-01-17 15:59:34
75%                2025-01-24 19:48:31
max                2025-02-01 23:44:11
Name: tpep_dropoff_datetime, dtype: object

In [20]:
#inconsistent data
trip25['duration'] = df_2025['tpep_dropoff_datetime']-df_2025['tpep_pickup_datetime']

In [21]:
trip25[trip25['duration'] == trip25['duration'].min()]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration
2029534,1,2025-01-23 01:44:59,2024-12-18 07:52:40,0.0,3.1,1.0,N,162,238,1,...,2.5,0.5,4.5,0.0,1.0,30.4,2.5,0.0,0.0,-36 days +06:07:41

In [22]:
# 4 days trips duration
trip25[trip25['duration'] == trip25['duration'].max()]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration
1858816,2,2025-01-21 12:23:41,2025-01-25 10:10:00,1.0,6.55,1.0,N,70,70,2,...,-5.0,-0.5,0.0,0.0,-1.0,-36.45,0.0,-1.75,0.0,3 days 21:46:19
1858817,2,2025-01-21 12:23:41,2025-01-25 10:10:00,1.0,6.55,1.0,N,70,129,2,...,5.0,0.5,0.0,0.0,1.0,36.45,0.0,1.75,0.0,3 days 21:46:19

In [23]:
df_2025["passenger_count"].describe()

count    2.935077e+06
mean     1.297859e+00
std      7.507503e-01
min      0.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      9.000000e+00
Name: passenger_count, dtype: float64

In [24]:
zero_passengers = df_2025[df_2025["passenger_count"] <= 0 ]
zero_passengers

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration
6,1,2025-01-01 00:14:47,2025-01-01 00:16:15,0.0,0.4,1.0,N,170,170,1,...,3.50,0.5,2.35,0.0,1.0,11.75,2.5,0.0,0.00,0 days 00:01:28
7,1,2025-01-01 00:39:27,2025-01-01 00:51:51,0.0,1.6,1.0,N,234,148,1,...,3.50,0.5,2.00,0.0,1.0,19.10,2.5,0.0,0.00,0 days 00:12:24
8,1,2025-01-01 00:53:43,2025-01-01 01:13:23,0.0,2.8,1.0,N,148,170,1,...,3.50,0.5,3.00,0.0,1.0,27.10,2.5,0.0,0.00,0 days 00:19:40
94,1,2025-01-01 00:11:27,2025-01-01 00:16:58,0.0,0.7,1.0,N,144,211,1,...,3.50,0.5,0.00,0.0,1.0,12.20,2.5,0.0,0.00,0 days 00:05:31
95,1,2025-01-01 00:19:30,2025-01-01 00:27:25,0.0,1.0,1.0,N,211,158,1,...,3.50,0.5,2.85,0.0,1.0,17.15,2.5,0.0,0.00,0 days 00:07:55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933984,1,2025-01-31 23:20:45,2025-01-31 23:45:28,0.0,3.9,1.0,N,144,50,1,...,4.25,0.5,2.50,0.0,1.0,33.65,2.5,0.0,0.75,0 days 00:24:43
2934049,1,2025-01-31 23:54:49,2025-02-01 00:09:35,0.0,6.4,1.0,N,263,232,1,...,4.25,0.5,2.00,0.0,1.0,35.95,2.5,0.0,0.75,0 days 00:14:46
2934589,1,2025-01-31 23:16:04,2025-01-31 23:36:38,0.0,2.4,1.0,N,68,114,1,...,4.25,0.5,4.25,0.0,1.0,25.60,2.5,0.0,0.75,0 days 00:20:34
2934590,1,2025-01-31 23:57:51,2025-02-01 00:08:06,0.0,1.6,1.0,N,142,236,1,...,3.50,0.5,3.10,0.0,1.0,18.80,2.5,0.0,0.00,0 days 00:10:15
2934894,1,2025-01-31 23:11:52,2025-01-31 23:37:36,0.0,6.3,1.0,N,68,112,1,...,4.25,0.5,5.00,0.0,1.0,40.35,2.5,0.0,0.75,0 days 00:25:44

In [25]:
na_passenger_count=df_2025[df_2025["passenger_count"].isna()]
na_passenger_count

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration
2935077,2,2025-01-01 00:39:17,2025-01-01 01:10:42,NaN,6.75,NaN,None,48,42,0,...,0.0,0.5,0.0,0.0,1.0,14.90,NaN,NaN,0.00,0 days 00:31:25
2935078,2,2025-01-01 00:33:40,2025-01-01 01:10:34,NaN,3.88,NaN,None,4,48,0,...,0.0,0.5,0.0,0.0,1.0,10.02,NaN,NaN,0.00,0 days 00:36:54
2935079,1,2025-01-01 00:09:32,2025-01-01 00:12:38,NaN,0.00,NaN,None,158,158,0,...,0.0,0.5,0.0,0.0,1.0,26.72,NaN,NaN,0.00,0 days 00:03:06
2935080,2,2025-01-01 00:21:42,2025-01-01 00:36:29,NaN,3.55,NaN,None,137,211,0,...,0.0,0.5,0.0,0.0,1.0,5.80,NaN,NaN,0.00,0 days 00:14:47
2935081,2,2025-01-01 00:56:04,2025-01-01 01:06:11,NaN,1.55,NaN,None,140,233,0,...,0.0,0.5,0.0,0.0,1.0,9.06,NaN,NaN,0.00,0 days 00:10:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475221,2,2025-01-31 23:01:48,2025-01-31 23:16:29,NaN,3.35,NaN,None,79,237,0,...,0.0,0.5,0.0,0.0,1.0,20.60,NaN,NaN,0.75,0 days 00:14:41
3475222,2,2025-01-31 23:50:29,2025-02-01 00:17:27,NaN,8.73,NaN,None,161,116,0,...,0.0,0.5,0.0,0.0,1.0,32.89,NaN,NaN,0.75,0 days 00:26:58
3475223,2,2025-01-31 23:26:59,2025-01-31 23:43:01,NaN,2.64,NaN,None,144,246,0,...,0.0,0.5,0.0,0.0,1.0,19.66,NaN,NaN,0.75,0 days 00:16:02
3475224,2,2025-01-31 23:14:34,2025-01-31 23:34:52,NaN,3.16,NaN,None,142,107,0,...,0.0,0.5,0.0,0.0,1.0,22.30,NaN,NaN,0.75,0 days 00:20:18
3475225,2,2025-01-31 23:56:42,2025-02-01 00:07:27,NaN,2.29,NaN,None,237,238,0,...,0.0,0.5,0.0,0.0,1.0,16.09,NaN,NaN,0.00,0 days 00:10:45

In [26]:
df_2025["trip_distance"].describe()

count    3.475226e+06
mean     5.855126e+00
std      5.646016e+02
min      0.000000e+00
25%      9.800000e-01
50%      1.670000e+00
75%      3.100000e+00
max      2.764236e+05
Name: trip_distance, dtype: float64

In [27]:
df_2025['duration'] = pd.to_timedelta(df_2025['duration'])

In [28]:
df_2025[(df_2025["trip_distance"] == 0) & (df_2025['duration'] <= pd.Timedelta(minutes=0) )]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration
92,1,2025-01-01 00:49:48,2025-01-01 00:49:48,1.0,0.0,1.0,Y,87,264,2,...,0.0,0.0,0.0,0.0,0.0,20.06,0.0,0.0,0.00,0 days
11604,1,2025-01-01 01:42:36,2025-01-01 01:42:36,1.0,0.0,1.0,N,158,264,2,...,3.5,0.5,0.0,0.0,1.0,8.00,2.5,0.0,0.00,0 days
13820,1,2025-01-01 02:13:25,2025-01-01 02:13:25,1.0,0.0,5.0,Y,233,264,2,...,0.0,0.0,0.0,0.0,0.0,114.00,0.0,0.0,0.00,0 days
14605,1,2025-01-01 02:09:52,2025-01-01 02:09:52,1.0,0.0,1.0,N,237,264,2,...,3.5,0.5,0.0,0.0,1.0,8.00,2.5,0.0,0.00,0 days
14607,1,2025-01-01 02:49:40,2025-01-01 02:49:40,1.0,0.0,1.0,N,162,264,2,...,3.5,0.5,0.0,0.0,1.0,8.00,2.5,0.0,0.00,0 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3447521,1,2025-01-31 07:43:50,2025-01-31 07:43:50,NaN,0.0,NaN,None,249,249,0,...,0.0,0.5,0.0,0.0,1.0,24.90,NaN,NaN,0.75,0 days
3449565,2,2025-01-31 08:05:00,2025-01-31 08:05:00,NaN,0.0,NaN,None,88,88,0,...,0.0,0.5,0.0,0.0,1.0,21.00,NaN,NaN,0.75,0 days
3450368,1,2025-01-31 10:58:58,2025-01-31 10:58:58,NaN,0.0,NaN,None,143,143,0,...,0.0,0.5,0.0,0.0,1.0,15.27,NaN,NaN,0.00,0 days
3459409,1,2025-01-31 18:55:38,2025-01-31 18:55:38,NaN,0.0,NaN,None,25,25,0,...,0.0,0.5,0.0,0.0,1.0,17.39,NaN,NaN,0.00,0 days
3475144,2,2025-01-31 23:44:00,2025-01-31 23:44:00,NaN,0.0,NaN,None,137,137,0,...,0.0,0.5,0.0,0.0,1.0,18.55,NaN,NaN,0.75,0 days

In [29]:
airport_fee_negative=df_2025[df_2025["Airport_fee"] < 0]
airport_fee_negative

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration
1061,2,2025-01-01 00:05:15,2025-01-01 00:23:39,1.0,7.79,1.0,N,138,24,4,...,-6.0,-0.5,0.0,-6.94,-1.0,-48.59,0.0,-1.75,0.0,0 days 00:18:24
1231,2,2025-01-01 00:30:37,2025-01-01 01:04:46,1.0,16.70,1.0,N,132,225,4,...,-1.0,-0.5,0.0,0.00,-1.0,-70.25,0.0,-1.75,0.0,0 days 00:34:09
2028,2,2025-01-01 00:08:22,2025-01-01 00:10:16,2.0,0.03,1.0,N,138,138,4,...,-6.0,-0.5,0.0,0.00,-1.0,-12.95,0.0,-1.75,0.0,0 days 00:01:54
2659,2,2025-01-01 00:15:00,2025-01-01 00:30:09,1.0,5.58,1.0,N,132,215,3,...,-1.0,-0.5,0.0,0.00,-1.0,-28.25,0.0,-1.75,0.0,0 days 00:15:09
2826,2,2025-01-01 00:12:24,2025-01-01 00:49:59,2.0,15.24,1.0,N,132,149,2,...,-1.0,-0.5,0.0,0.00,-1.0,-66.05,0.0,-1.75,0.0,0 days 00:37:35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2934580,2,2025-01-31 23:03:25,2025-01-31 23:12:42,1.0,5.95,1.0,N,132,28,4,...,-1.0,-0.5,0.0,0.00,-1.0,-27.55,0.0,-1.75,0.0,0 days 00:09:17
2934819,2,2025-01-31 23:49:18,2025-02-01 00:15:34,1.0,17.12,2.0,N,132,74,4,...,0.0,-0.5,0.0,-6.94,-1.0,-80.19,0.0,-1.75,0.0,0 days 00:26:16
2934937,2,2025-01-31 23:57:09,2025-01-31 23:57:19,1.0,0.00,2.0,N,138,138,4,...,0.0,-0.5,0.0,0.00,-1.0,-73.25,0.0,-1.75,0.0,0 days 00:00:10
2934973,2,2025-01-31 23:36:56,2025-01-31 23:50:36,4.0,4.70,1.0,N,132,130,2,...,-1.0,-0.5,0.0,0.00,-1.0,-24.75,0.0,-1.75,0.0,0 days 00:13:40
2935006,2,2025-01-31 23:10:12,2025-01-31 23:10:40,1.0,0.00,1.0,N,132,132,4,...,-1.0,-0.5,0.0,0.00,-1.0,-7.25,0.0,-1.75,0.0,0 days 00:00:28

In [30]:
df_2025["PULocationID"].describe()

count    3.475226e+06
mean     1.651916e+02
std      6.452948e+01
min      1.000000e+00
25%      1.320000e+02
50%      1.620000e+02
75%      2.340000e+02
max      2.650000e+02
Name: PULocationID, dtype: float64